[server]
broker = "mqtt://mqtt:2883"
identity = "mud@ha"
log_level = "debug"
log_format = "text"
log_output = "stdout"
log_utc = true

[modules.playlist]
enabled = true
name = "HA Playlists"
provider = "playlist"
resource = "local"
storage_path = "/config/playlists"

[modules.renderer_gstreamer]
enabled = true
name = "HA Renderer"
provider = "gstreamer"
resource = "default"
pipeline = "playbin uri={url} volume={volume} audio-sink=pulsesink video-sink=fakesink"
publish_state = true
